version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    image: queryexpnopt-postgres:16-hypopg
    container_name: queryexpnopt-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: queryexpnopt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: UTC
      # optional: initdb args (UTF-8, locale); only used on first run
      # POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5433:5432"   # Use port 5433 on host to avoid conflict
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-queryexpnopt}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # API (enable when you wire /explain to the DB)
  # api:
  #   build: .
  #   container_name: queryexpnopt-api
  #   environment:
  #     DB_URL: postgresql+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-queryexpnopt}
  #     LLM_PROVIDER: dummy
  #     APP_ENV: development
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - ./src:/app/src:rw

volumes:
  postgres_data:
